# curl -d @/Users/paulwalk/_temp/throwing-muses-electric-ballroom-camden.zip -H "Content-Type: application/zip" 
#     -X POST http://localhost:3000/ingest/repo_for_testing_webhooks
POST https://sheepstor.paulwalk.net/ingest/dev.paulwalk.net
Content-Type: application/zip
Authorization: Bearer {{BEARER_TOKEN}}

< /Users/paulwalk/_temp/test-blog-post.zip
###